spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  batch:
    initialize-schema: always
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://125.129.2.104:3306/WEBDB?serverTimezone=Asia/Seoul&useSSL=false&autoReconnection=true
    username: web_user
    password: web123!
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
    open-in-view: false

logging.level:
  org.hibernate.SQL: debug #SQL log? ??.
  org.hibernate.type: trace #SQL parameters ?? ??