spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  batch:
    initialize-schema: always # 운영환경에서는 never 로 변경
    job:
      names: ${job.name:NONE}
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/test
      username: sa
      password:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://125.129.2.104:3306/WEBDB?serverTimezone=Asia/Seoul&useSSL=false&autoReconnection=true
#    username: web_user
#    password: web123!
#    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    user:
      name: reservation_ad
      password: 1234
  cache:
    redis:
      cache-null-values: true
  redis:
    host: 127.0.0.1
    port: 6379
    #caches: token_cache,menu_cache

logging.level:
  org.hibernate.SQL: debug #SQL log? ??.
  org.hibernate.type: trace #SQL parameters ?? ??
